### ISSUE TITLE
Ensure that aepp running in iOS Cordova app doesn't have access to Cordova bridge

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-base#1098]
In the investigation of the same issues for Android (#1097), I have found that `<allow-navigation />` applies also for giving access to the bridge. If it the same for iOS so aepps has access to the bridge because for some reason we have to use `<allow-navigation href="*" />` in iOS configuration.

Related code should be in https://github.com/apache/cordova-plugin-wkwebview-engine package.

**Comment by etharner** [comment]
As I found, https://github.com/apache/cordova-plugin-wkwebview-engine uses `window.webkit.messageHandlers.cordova.postMessage` ([https://github.com/apache/cordova-plugin-wkwebview-engine/blob/master/src/www/ios/ios-wkwebview-exec.js#L121]) which will send messages to native code message handler registered through `WKUserContentController` 

[https://github.com/apache/cordova-plugin-wkwebview-engine/blob/dc8b2777bcea9fe2dce4fe5bac6cf548d9d43621/src/ios/CDVWKWebViewEngine.m#L93]() 
[https://developer.apple.com/documentation/webkit/wkusercontentcontroller]()

When iframe tries to call `window.webkit.messageHandlers.cordova.postMessage`, this call rejects with `SecurityError: Blocked a frame with origin from accessing a cross-origin frame. Protocols, domains, and ports must match.`

**Comment by etharner** [comment]
Update: `window.webkit.messageHandlers.cordova.postMessage` is working. SecurityError was related to other code.
Thus, user can access cordova bridge through this method. For example: `window.webkit.messageHandlers.cordova.postMessage(['8', 'Clipboard', 'copy',  ["test"]]);` will copy `test` to clipboard of user who opened aepp with this code in aepp browser. You can try this with deployed aepp example on `https://test-bridge-aepp.origin.aepps.com` using cordova ios version of Base Aepp.
