### ISSUE TITLE
Network Switch Block Polling

### ISSUE THREAD

**Issue by muxe** [aeternity/aepp-base#110]
When checking #109 I found this strange behavior when you change the network, in the development tools you can see that the app is polling new blocks from the old and the new network. When you switch networks a lot you get a lot of useless calls.
I think this comes from the [getter](https://github.com/aeternity/aepp-identity/blob/stage/src/store/index.js#L51) in the store. The app uses the new web3 object but the old one is still alive and keeps polling

![screenshot from 2018-05-02 13-07-01](https://user-images.githubusercontent.com/356123/39520125-c59bee3c-4e09-11e8-97e1-f88b0d2e5adf.png)

**Comment by CedrikNikita** [comment]
App behaviour have changed since that issue a lot. RIght now there is no evidence of this issue.
