### ISSUE TITLE
Cannot claim a name (13 chars or longer) with 0.17.2

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#1278]
I get a msg that the name is registered and pointed... but it does not show up in my names list... I also get a msg that the name is registered when I try to register it again... This happened for transcendental.chain

**Comment by CedrikNikita** [comment]
https://github.com/aeternity/aepp-middleware/issues/228

**Comment by davidyuk** [comment]
Mostly probable that this was fixed on the middleware side.
