### ISSUE TITLE
Legacy token migration URL

### ISSUE THREAD

**Issue by dincho** [aeternity/aepp-base#1367]
The legacy token migration URL is still used in the code (button link), please change it to ASAP migrate.aeternity.com

As the legacy one will be shutdown very soon.

https://github.com/aeternity/aepp-base/blob/9e84c85d1e25d83948559311a582b950df903f15/src/components/mobile/MigratedBalanceModal.vue#L15

Related to https://github.com/aeternity/aepp-base/issues/1313 and https://github.com/aeternity/aepp-base/pull/1316

**Comment by davidyuk** [comment]
the whole component was removed, so it is not actual any more
