### ISSUE TITLE
missing signing confirmation

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-base#1398]
the new version `v0.24.0` introduced a web wallet. we are currently testing the AEX-2 connection and I used the **web wallet** to perform a name-claim within aenalytics. I was confused when testing it because I didn't have to confirm the transactions. the transaction was immediately submitted without requiring an additional user-input to confirm/deny the proposed transaction.

the second problem is that when I tried to do the same thing with an active **remote connection** I didn't get any confirmation modal on my smartphone (iOS `v.0.23.0`) so I wasn't possible to confirm the transaction and we never receive the callback. the question here is whether this would be solved when using iOS `v0.24.0` (not available yet) or whether this would still be a problem.

**Comment by marc0olo** [comment]
@etharner @mradkov was that working on your end? hasn't this been tested? can you elaborate a bit more about the problem if you need help?

**Comment by mradkov** [comment]
Did you try the TestFlight version 0.24.0?

**Comment by marc0olo** [comment]
no, I don't know how to get the testflight version. can you provide me the invite link?

**Comment by mradkov** [comment]
> no, I don't know how to get the testflight version. can you provide me the invite link?

https://testflight.apple.com/join/2SGMknRk

**Comment by marc0olo** [comment]
same problem with testflight version `0.24.0`. I don't get a confirmation modal in the mobile app. this used to work before we integrated AEX-2

have you tested signing with an active remote connection? @etharner

**Comment by mradkov** [comment]
Tried reproducing, but remote connection signing confirmation works for me 🤷 
<img width="822" alt="Screenshot 2020-06-19 at 18 04 19" src="https://user-images.githubusercontent.com/13139371/85147546-b235f180-b257-11ea-9afc-4cf9618e751c.png">
![IMG_8378](https://user-images.githubusercontent.com/13139371/85147527-aba77a00-b257-11ea-973d-465ea0b2db6a.PNG)
<img width="757" alt="Screenshot 2020-06-19 at 18 04 30" src="https://user-images.githubusercontent.com/13139371/85147553-b3671e80-b257-11ea-8fd5-557a38f7d273.png">

**Comment by marc0olo** [comment]
ok this is interesting. I can confirm it works when I send using the web-interface of the base aepp.

in our case we still create the reverse iFrame and perform a "spy" using the AEX-2 wallet detector. the connection to the wallet seems to be working. but when trying to execute a transaction we don't get the confirmation modal on the mobile app.

**Comment by etharner** [comment]
This issue is related to broken release uploaded. Version has changed, but other stuff (updated sdk, naming system on desktop etc. hasn't been uploaded). We fixed it, please recheck on https://base.aepps.com/.

**Comment by mradkov** [comment]
> This issue is related to broken release uploaded. Version has changed, but other stuff (updated sdk, naming system on desktop etc.) hasn't been uploaded. We fixed it, please recheck on https://base.aepps.com/.

The release build was updated and uploaded.

**Comment by marc0olo** [comment]
Thanks, I will have a check and come back to you.

Was this already resolved early in the morning? Because my teammate told me that he was able to send AE using remote connection this morning. I was very confused then :D 

---------------

@etharner should the updated release now also require a confirmation when using the web-wallet? just asking because I mentioned 2 different problems here

**Comment by etharner** [comment]
> Thanks, I will have a check and come back to you.
> 
> Was this already resolved early in the morning? Because my teammate told me that he was able to send AE using remote connection this morning. I was very confused then :D
> 
> @etharner should the updated release now also require a confirmation when using the web-wallet? just asking because I mentioned 2 different problems here

Yes, confirmation modals on dekstop is one of this release features.

**Comment by marc0olo** [comment]
I can confirm that the problems are solved now. thanks!
