### ISSUE TITLE
Recover should be the primary action

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-base#144]
Recover should be the primary action instead of account creation because our accounting is based on [BIP-44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki) that makes to use the same mnemonic in a safe way for accounts in different cryptocurrencies, and other cryptography related services.
![screenshot from 2018-06-20 16-42-20](https://user-images.githubusercontent.com/9007851/41665762-0a1a25e0-74a9-11e8-938d-f56c7a9a1fa9.png)

**Comment by dadaphl** [comment]
interesting idea. @raymundjacobs what do you think?

**Comment by davidyuk** [comment]
Implemented in the current version
