### ISSUE TITLE
After update of the base app, page does not display the app

### ISSUE THREAD

**Issue by sadiqevani** [aeternity/aepp-base#210]
- User visited the page this morning around 12PM (noon), and the base app worked correctly
- Then user visited the page a few hours later and it kept showing a blank page
- When it was tried on the incognito mode, the base-app was loaded correctly.

My assumptions are that the issue has to do with the cache, I opened the base app though desktop and was greeted with an "update" notification.

**Comment by davidyuk** [comment]
Would be great to see that was in the console of that user. He has visited MVP version or http://stage-identity.aepps.com? Issue solved by #207 has the completely same behavior.

**Comment by sadiqevani** [comment]
@davidyuk 

It was opened from a mobile phone and I couldn't debug it, and the user visited the https://base.aepps.com/#/ not the staging environment.

**Comment by davidyuk** [comment]
It can be a cache issue. @emil-apeunit how MVP version is currently deployed? How I can reproduce it?

**Comment by j28** [comment]
we should check this right after next release. i am adding a label for it.

**Comment by sadiqevani** [comment]
This is an outdated ticket, I think its fixed and was not due to anything within the app, but a caching issue.

**Comment by j28** [comment]
I see. I think we should double check that this does not happen again (regardless if it's based on a caching mechanism) after the next release. Thanks!

**Comment by j28** [comment]
This happened after release 0.8.0 for me, but not after release 0.8.1 in web.

**Comment by davidyuk** [comment]
We didn't notice this issue in the recent time
