### ISSUE TITLE
recovery verification: non-dismissible "too fast" modal 

### ISSUE THREAD

**Issue by pascuin** [aeternity/aepp-base#216]
The "too fast" modal cannot be closed by pressing "OK". Android back button navigates back the page behind the modal on Android 8.0  

a small note, I think "to fast" should be "too fast" 

Issues:
- [x] modal cannot be closed by pressing "OK"
- [ ] Android back button navigates back the page behind the modal
- [x] "to fast" should be "too fast"

![image](https://user-images.githubusercontent.com/9214127/49175870-d49cad00-f349-11e8-867e-b2a08896c50f.png)

**Comment by CedrikNikita** [comment]
Close this issue and reopen remaining problem #576
