### ISSUE TITLE
Create a screen for contract method call

### ISSUE THREAD

**Issue by edwarddikgale** [aeternity/aepp-base#279]
Child of #276

**Comment by edwarddikgale** [comment]
Denis has implemented this however with no designs and might need upgrade ticket/story when new design comes

**Comment by raymundjacobs** [comment]
@davidyuk Can you please describe the case and show me the current status in the form of a screenshot? So I have more context. Thanks!

**Comment by davidyuk** [comment]
@raymundjacobs after merging of #344 it looks like this:

<img src="https://user-images.githubusercontent.com/9007851/52558235-06260000-2df2-11e9-8549-0425e9c54ec6.png" width="50%" />

I'm closing this ticket for now, if you have some improvements let's make a separate one.
