### ISSUE TITLE
Show sub account balances if any

### ISSUE THREAD

**Issue by edwarddikgale** [aeternity/aepp-base#294]

**Comment by edwarddikgale** [comment]
This is very important! In the base aepp when a user derives an account and transfers fees to this(these) account(s), leave the app and come back... they can't see the accounts. Its as if the funds are lost. The users need to be able to have their derived accounts visible as long as they have some funds in them. @thepiwo has a solution for this...

**Comment by j28** [comment]
rephrase: accounts that the user made do not get added to the wallet after seed recovery.

**Comment by thepiwo** [comment]
I think the HD Wallet BIPs in Bitcoin describe some standard of how to look for child accounts, similar to: check the next 5 as long as one of them has balance or nonce greater zero

**Comment by j28** [comment]
@thepiwo is this the same as #379 ?

**Comment by thepiwo** [comment]
@j28 it is

**Comment by j28** [comment]
Thanks @thepiwo I moved the contents of this one to the other one and am closing this one (duplicate).
