### ISSUE TITLE
Implement header bar in Browser

### ISSUE THREAD

**Issue by raymundjacobs** [aeternity/aepp-base#305]
Child of #312

**Comment by raymundjacobs** [comment]
The header bar is a bar which is part of the Base æpp. The æpp start below the bar. When the user scrolls down within the æpp, the bar slides up. When the user scrolls up again, the bar should appear again.  The Header bar is needed for the user to:

1. Bookmark the æpp (add to the browser home screen)
2. Go back to the browser home screen.

**Comment by raymundjacobs** [comment]
Designs: https://app.zeplin.io/project/59e4cf99fc0bb2f99a89551b/dashboard?seid=5c1d175ea493040a8b7aa803

**Comment by davidyuk** [comment]
Child of #281
