### ISSUE TITLE
Implement Transaction History

### ISSUE THREAD

**Issue by raymundjacobs** [aeternity/aepp-base#308]
Child of #306

**Comment by raymundjacobs** [comment]
Needs investigation from Denis. Middleware's Tx history has pagination?

**Comment by raymundjacobs** [comment]
Updated Transfer screen: https://zpl.io/beodppl

**Tx History**
Start state: https://zpl.io/2ZjGAlL
Scolled up state: https://zpl.io/2yOmoYy

**Tx Detail**
Received TX: https://zpl.io/VKPqBWJ & https://zpl.io/2GyQqxJ
Spend tx: https://zpl.io/VKPq9pE

**Comment by davidyuk** [comment]
> Middleware's Tx history has pagination?

It is implemented in the middleware according to:
https://github.com/aeternity/aepp-blockchain-explorer/blob/11f7117525c0142a5e3e791fdedde1fac6808dd8/src/store/modules/accounts/actions.js#L37

but for the beginning, I think we won't implement it.

**Comment by j28** [comment]
status update: detail view is left. business logic and list view(s) are complete.
