### ISSUE TITLE
Fix aepp browser in desktop version

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-base#317]
> philipp.piwowarsky 1:46 PM
If I open via the absolute link it works when I assign a specific height to the iframe, otherwise its 0px high.

**Comment by j28** [comment]
@davidyuk could you put a screenshot so that we can better understand the issue (and can prioritize fixing it accordingly)?

**Comment by davidyuk** [comment]
We don't have an intentional implementation of aepp browser in desktop version of Base app. I think it should be suppressed by reverse iframe approach.
