### ISSUE TITLE
Implement notification on desktop: use chrome

### ISSUE THREAD

**Issue by raymundjacobs** [aeternity/aepp-base#320]
Child of #312

**Comment by raymundjacobs** [comment]
See #313

**Comment by raymundjacobs** [comment]
Design: https://zpl.io/am9mwWK

**Comment by davidyuk** [comment]
@raymundjacobs looks like assets can't be exported

**Comment by raymundjacobs** [comment]
@davidyuk Updated design: https://zpl.io/2G9NdAr

In this case we only show the message when the user tries to connect the ledger in a browser which does not support the ledger.
