### ISSUE TITLE
Implement modal background according to designs

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-base#370]
https://app.zeplin.io/project/59e4cf99fc0bb2f99a89551b/screen/5c335ed83b357842528afd64

**Comment by j28** [comment]
@davidyuk is this a reusable element/component which once implemented we can use in various views OR is it specific to the example in the design (and not so easily reusable once implemented there)?

**Comment by davidyuk** [comment]
This background should be used in all modals on mobile, [lately](https://github.com/aeternity/aepp-base/pull/548/commits/681fbf727d4095f9105a6aa5240845dcbc722d04#diff-47cbebac3b247cf8d761f771afd628f3R29), we have implemented something similar.

Overall these designs look overcomplicated, instead of 4 layers we can use just two without a significant difference as I see:

| According to designs | Our implementation |
| --------------------- | -------------------- |
| ![according zeplin](https://user-images.githubusercontent.com/9007851/56271189-2925a680-60f8-11e9-8614-7e7d1394751c.png) | ![currently](https://user-images.githubusercontent.com/9007851/56271195-2e82f100-60f8-11e9-9834-6cf0fdfef2f7.png) |

**Comment by j28** [comment]
Looks good to me. I can barely tell the difference.
