### ISSUE TITLE
Implement account discovery

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-base#379]
[Updated for clarity]

Rephrase: accounts that the user made do not get added to the wallet after seed recovery.

Implementation links and comments:
https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki#account-discovery

Via @thepiwo :
I think the HD Wallet BIPs in Bitcoin describe some standard of how to look for child accounts, similar to: check the next 5 as long as one of them has balance or nonce greater zero

Via Eddie:
This is very important! In the base aepp when a user derives an account and transfers fees to this(these) account(s), leave the app and come back... they can't see the accounts. Its as if the funds are lost. The users need to be able to have their derived accounts visible as long as they have some funds in them. @thepiwo has a solution for this...

**Comment by j28** [comment]
Currently if a user tries to recover their account the derived (user-created) accounts they made will not be shown inside the recovered account (inside the Base aepp).
