### ISSUE TITLE
Implement wording updates: contacts

### ISSUE THREAD

**Issue by boyhulsteijn** [aeternity/aepp-base#388]
Child of #458

**Comment by boyhulsteijn** [comment]
New text and small design updates.

Screens:
v0.6.x-04.01-Contacts
v0.6.x-04.02-Contacts
v0.6.x-04.03-Contacts
v0.6.x-04.04-Contacts
v0.6.x-04.05-Contacts

**Comment by CedrikNikita** [comment]
closed by #947
