### ISSUE TITLE
Allow setting Custom Node URL

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-base#446]
2 reasons: 

0. As a decentralized protocol, we should not force user to use our node infrastructure as that's also not really smart (censorship/DDoS/ single point of failure in general)

1. When developing my æpp, I'd would want to test it in base app on the same environment (= private test chain) my team used to build it upon. Advantages: No redeployment, same old state, I'm the boss around, etc.

This feature does not have to be heavily promoted, **BUT (important):**  Show some icon indicating that a user is NOT on the mainnet right now. This is the case if a) our node infrastructure is not used or b) the net the currently used node is connected to does not meet criteria (pick one/some) we check it for and compare it to our own data remotely. (this is important so no one will be tricked onto a fake mainnet)

**Comment by edwarddikgale** [comment]
already exists

**Comment by nikita-fuchs** [comment]
Know better now, my bad.

Am Mo., 11. März 2019, 14:11 hat edwarddikgale <notifications@github.com>
geschrieben:
