### ISSUE TITLE
Implement NS MVP mini æpp inside Base æpp

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#465]
Originally part of #464

**Comment by j28** [comment]
The designs are in Zeplin. We also need to add the following notifications:

Notification upon claim submission
icon: in progress (recycling button)
heading: Your name registration is in progress!
text: You will receive another notification when the claim is complete.
button: View Transaction

Notification upon registration success
icon: checkmark
heading: Your name registration was successful!
text: View your names in the Names tab and share them to receive funds.
button: View Names

**Comment by j28** [comment]
blocked by: https://github.com/aeternity/aepp-middleware/issues/83

**Comment by CedrikNikita** [comment]
closed by #919
