### ISSUE TITLE
Minimal, standard transaction fee needs to be higher

### ISSUE THREAD

**Issue by eminogrande** [aeternity/aepp-base#467]
the minimum is too low fore some aepps like the demo for the dronegraffiti aepp.

**Comment by davidyuk** [comment]
As I know, aepp can set tx fee by itself and it will be preserved by Base app while signing, so fees can be increased on the side of aepp. Also, Base app uses JS SDK for [calculation of minimum tx fee](https://github.com/aeternity/aepp-base/blob/626ec07918586629d1ff21ee0a4acdc77b401d57/src/store/plugins/initSdk.js#L88-L90), probably it better to solve on their side.

Or you mean that generated fees are acceptable by node but gets mined in too long time? In that case, we can implement some algorithm that will suggest a fee, based on the last 100 mined transactions (for example). This stuff is better to put into SDK as well.

cc: @nduchak

**Comment by davidyuk** [comment]
probably it can be fixed by #472

**Comment by davidyuk** [comment]
@thepiwo is it still actual?

**Comment by thepiwo** [comment]
I think this has already been resolved
