### ISSUE TITLE
Inappropriate custom node issue

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-base#468]
If user created inappropriate (for any reason node), then base app stay on the previous one. For users it is shown that we are on this custom (inappropriate) node. Base app should not allow such misunderstanding.
![Custom node](https://user-images.githubusercontent.com/9008074/54748413-4fe9dd80-4c1d-11e9-803b-a532019014e4.gif)
Parts of issue:
- [x] SDK instance should be reset if connected to a broken node
- [x] all cached data that fetched from an old node should be removed

**Comment by davidyuk** [comment]
I see two major parts of this issue:
- SDK instance should be reset if connected to a broken node
- all cached data that fetched from an old node should be removed

The first one is fixed in #570

**Comment by CedrikNikita** [comment]
The second issue was fixed in #605
