### ISSUE TITLE
Cordova iOS: Empty spaces on top and bottom of iPhone X-like screen

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-base#476]
![image](https://user-images.githubusercontent.com/7098449/54911889-24c3fe80-4f3b-11e9-8555-52ed3c740b46.png)
![image](https://user-images.githubusercontent.com/7098449/54911902-2a214900-4f3b-11e9-9ee4-e710c091ae89.png)

**Comment by j28** [comment]
i built this in iphone x and now i see a space above the ui area. see below.

can we remove the white space at the top?

![Screen Shot 2019-03-28 at 10.39.50 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456fb6b7191a379ef0c2858415a4ebc21254d58eeb9cb74fce36f34985619e8826f0973c33c14acb8801cbd53ba21df1a82b4bd8a1ec0fa2137a5dad11b61435c52dcbd4f3fb29b49c259f34ee24555ad113263e376346e0a.png)
![Screen Shot 2019-03-28 at 10.41.59 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456fb6b7191a379ef0c2f50415a47bc21254d58eeb9cb74fce36f34985619e8826f0973c33c14acb8801cbd53ba21df1a82b4bd8a1ec0fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee24555ad103e62e371316e0a.png)
