### ISSUE TITLE
Cordova iOS: Border turns black after clicking on ListItem

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-base#479]
![border](https://user-images.githubusercontent.com/7098449/55057137-046b7f80-50b4-11e9-9d02-65fbd0a29873.gif)

**Comment by j28** [comment]
i built this branch locally in iphone 8 simulator and the border is still there. see attached.
![Screen Shot 2019-03-28 at 10.22.13 PM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206456fb6b7191a379ef0c2953415e4dbc21254d58eeb9cb74fce36f34985619e8826f0973c33c14acb8801cbd53ba21df1a82b4bd8a1ec0fa2137a5dad11b61435c52dcbd4f3fb29842c259f34ee24555ac16376be171376e0a.png)
