### ISSUE TITLE
iPhone SE & Smaller Android Devices: Seed Validation, Button is Off Screen

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#486]
Can be reproduced using iOS Simulator or an Android device with a smaller screen.
![Screen Shot 2019-03-30 at 12.00.12 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206457f36b7191a379ed0c2b51415e4cbc30254d58eeb9cb74fce36f34985619e8826f0973c33c14acb8801cbd53ba21df1a82b4bd8a1ec0fa2137a5dad11b61435c52dcbd4f3fb29843c259f34ee24455a5143e63e5753e6e0a.png)

**Comment by davidyuk** [comment]
We are unsure how to fix it. Should button we fixed on the screen bottom or we should collapse content somehow?

**Comment by j28** [comment]
this will be fixed when #550 is fixed/closed.
