### ISSUE TITLE
iPhone SE in Simulator: Strange behavior of password input fields

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#487]
Can be reproduced via iPhone Simulator > iPhone SE device.
![Screen Shot 2019-03-30 at 12.00.20 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206457f36b7191a379ed0c2b51415d4ebc30254d58eeb9cb74fce36f34985619e8826f0973c33c14acb8801cbd53ba21df1a82b4bd8a1ec0fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee24455a51a3762e576326e0a.png)

**Comment by davidyuk** [comment]
looks like an issue of `sticky` positioning, probably better to use `fixed` instead
