### ISSUE TITLE
iPhone SE & Android Small Screen: Transfer > Receive... address does not render properly.

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#489]
You can use iPhone SE Simulator or a small screen Android to reproduce.
![Screen Shot 2019-03-30 at 12.01.58 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206457f36b7191a379ed0c2b50415a46bc30254d58eeb9cb74fce36f34985619e8826f0973c33c14acb8801cbd53ba21df1a82b4bd8a1ec0fa2137a5dad11b61435c52dcbd4f3fb2984cc259f34ee24455a6123e66e57e376e0a.png)

**Comment by CedrikNikita** [comment]
Other variants of fixes:
1)
![photo_2019-04-01_16-55-55](https://user-images.githubusercontent.com/9008074/55308778-11ff7b80-549f-11e9-890e-2cd0c4c54a26.jpg)
2)
![photo_2019-04-01_16-56-00](https://user-images.githubusercontent.com/9008074/55308800-1e83d400-549f-11e9-96f3-e5bb2474394b.jpg)
3)
![photo_2019-04-01_16-56-07](https://user-images.githubusercontent.com/9008074/55308820-26437880-549f-11e9-91b4-815b5c400d3a.jpg)

**Comment by j28** [comment]
is this fixed now? i built using commit e631105fb7d1d4acbeed9a45d7f3ecee2dac02ca and i see the below in iPhone SE.

I like variant 1 above.

<img width="504" alt="Screen Shot 2019-04-02 at 10 06 32 PM" src="https://user-images.githubusercontent.com/1156607/55432860-4a34b600-5594-11e9-8ca7-3f36daf7d621.png">
