### ISSUE TITLE
iPhone: Add intro screen

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#495]
![Screen Shot 2019-03-30 at 1.16.24 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206457f36b7191a379f1132d4f5d5b5edd3c4a4356bcbbd671f3e57862804e0ebed33b5871c73811acba811ded01bb74de4887b7bcd84cd2f42f67b6d5db1063474f4dcbed5727a29841c95df348e84d50a4103163e5772431.png)

**Comment by davidyuk** [comment]
the same as #496 :
![Simulator Screen Shot - iPhone SE - 2019-04-01 at 16 43 01](https://user-images.githubusercontent.com/9007851/55308201-4ffba000-549d-11e9-96ff-1fc07891f0d8.png)
