### ISSUE TITLE
iPhone: Add app icon

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#496]
![Screen Shot 2019-03-30 at 1.16.16 AM.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5c34c7458a6d740014df7850/125516c66e82c728ace21e0d46db978826878de9bce1b057e40fa0c5700b77206457f36b7191a379f1132d4f5e595edd3c4a4356bcbbd671f3e57862804e0ebed33b5871c73811acba811ded01bb74de4887b7bcd84cd2f42f67b6d5db1063474f4dcbed5727a19e41c95df348e84d50a4133f6ae2752431.png)

**Comment by davidyuk** [comment]
Try to build it after running `npm run gen:cordova-resources`:
![Simulator Screen Shot - iPhone SE - 2019-04-01 at 16 21 41](https://user-images.githubusercontent.com/9007851/55307285-70762b00-549a-11e9-84c6-98ed320ef0bb.png)
