### ISSUE TITLE
Should a page be scrolled up when navigating between pages?

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-base#518]
Example:

| Send screen | Choosing an own account | The next screen is scrolled down | How it can look if scrolled up |
| --- | --- | --- | --- |
| ![localhost_8080_ (2)](https://user-images.githubusercontent.com/9007851/55532488-60369980-56ae-11e9-99bf-48b4d14eed8e.png) | ![localhost_8080_ (3)](https://user-images.githubusercontent.com/9007851/55532489-60369980-56ae-11e9-8109-66168da172ab.png) | ![localhost_8080_ (4)](https://user-images.githubusercontent.com/9007851/55532490-60369980-56ae-11e9-80e6-5d55f113e9a4.png) | ![localhost_8080_ (5)](https://user-images.githubusercontent.com/9007851/55532491-60cf3000-56ae-11e9-8deb-8c7d72ecf35b.png) |

**Comment by j28** [comment]
I just reviewed this in the app itself. I think it should be scrolled.

**Comment by j28** [comment]
I looked at this on iPhone 7+. I think it's fine the user gets scrolled up for now.
