### ISSUE TITLE
[Dependency] Transaction history does not work in iOS build uploaded to TestFlight or local iOS build

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#555]
After sending a transaction the history stays blank in all views.

**Comment by j28** [comment]
action: speak with john about when the middleware will be adjusted.

**Comment by j28** [comment]
mitia is talking with john about deploying the adjustment.

**Comment by davidyuk** [comment]
a ​related issue in middleware repository: https://github.com/aeternity/aepp-middleware/issues/32

**Comment by davidyuk** [comment]
it looks working now on testnet:
![photo_2019-04-25_11-42-32](https://user-images.githubusercontent.com/9007851/56726542-3faeac00-674f-11e9-8db2-3eed977577f5.jpg)

**Comment by etharner** [comment]
It works for testnet, but not in mainnet. I think John simple hasn't released mainnet version yet.

**Comment by j28** [comment]
this finally works with the mainnet... hooray!
