### ISSUE TITLE
Rendering of transfer view breaks immediately after creating a new sub account 

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#566]

**Comment by j28** [comment]
![Image](https://i.imgur.com/fGI1qxR.jpg)
![Image](https://i.imgur.com/PzyyBWb.jpg)

**Comment by j28** [comment]
To reproduce:

1) go to transfer view 
2) make me sub account 
3) look at transfer view immediately after the sub account is created 

This issue appear in both iOS and Android.

**Comment by davidyuk** [comment]
@j28 instead of manual building, you can try version built by Jenkins for simulators: http://stage-identity.aepps.com/aeternity.app.tar.gz

**Comment by j28** [comment]
i cannot reproduce this anymore either. closing for now.
