### ISSUE TITLE
aepp can currently open on its own (instead of inside base aepp)

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-base#572]
![Href in location](https://user-images.githubusercontent.com/9008074/56106320-e17e0e00-5f83-11e9-8344-d97300a5acad.gif)

**Comment by j28** [comment]
short term fix: limit aepps domains (which can be accessed) in cordova.

**Comment by davidyuk** [comment]
it should be fixed by getting rid of iframes (#718)
