### ISSUE TITLE
User should be able to sign tx inside voting aepp using Airgap on same device

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#595]

**Comment by j28** [comment]
best option is if airgap changes code on their side:
+ more than one destination for wallet sync
+ implement callback

fallback:
+ copy and paste for user, but it's confusing because user is choosing "separate device" instead of same.

**Comment by j28** [comment]
pinged @AndreasGassmann on dev chat to get a sense of the likelihood of code changes on airgap's side + a potential timeline for these changes.

**Comment by pascuin** [comment]
@j28 copy pasting already works for the sync QR and transaction QR codes, it's a bit hidden as we mostly use this for testing and some integration purposes.

The Sync code can be copied through the overflow menu or simply clicking on the QR code, this also applies to transaction QR codes for both Vault and Wallet.

![image](https://user-images.githubusercontent.com/9214127/57430213-4816e480-722f-11e9-8270-84ddb01c864f.png)

Pasting can be done through the Settings screen with "Paste from clipboard".

![image](https://user-images.githubusercontent.com/9214127/57430209-40574000-722f-11e9-966c-34a059d72a26.png)

Let's continue the conversation with @AndreasGassmann how we can improve the user experience for this.

**Comment by AndreasGassmann** [comment]
Hi @j28. Are you looking for a way to do that when using the base aepp as a native app or as a webapp?

If it is only required to do it in the native app, you could just register the "airgap-wallet://" scheme.

**Comment by davidyuk** [comment]
@AndreasGassmann I think we need this for both cases. From the beginning, we were thinking about registering itself as a handler of airgap-wallet protocol, until we have checked it support in mobile browsers.

**Comment by AndreasGassmann** [comment]
So in this case we probably have to introduce a new "shareWalletRequest" type that also includes a callback URL.
