### ISSUE TITLE
`grayscale` filter on Page for some reason moves ButtonAddFixed

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-base#601]
| | |
|-|-|
| ![localhost_8080_(iPhone 6_7_8) (1)](https://user-images.githubusercontent.com/9007851/56412372-2bb50700-6284-11e9-8829-944b9151e7a2.png) | ![localhost_8080_(iPhone 6_7_8) (2)](https://user-images.githubusercontent.com/9007851/56412376-2e176100-6284-11e9-805f-933e86a75b6e.png) |

**Comment by CedrikNikita** [comment]
There is no such issue in current version.
