### ISSUE TITLE
Authentification with Ledger on firefox with enable u2f support, disturbing message every 4 seconds

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-base#640]
![Disturbing](https://user-images.githubusercontent.com/9008074/56879933-26369880-6a9e-11e9-95a5-9132e0f8a367.gif)

![image](https://user-images.githubusercontent.com/9008074/56879927-220a7b00-6a9e-11e9-9b68-26ba3d10ff2c.png)

**Comment by j28** [comment]
Message should appear every 30 seconds (not every 4 seconds)
