### ISSUE TITLE
TabBar from mobile appears in desktop Contacts after refreshing

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-base#643]
![image](https://user-images.githubusercontent.com/9008074/56881166-f047e300-6aa2-11e9-8f14-53ee1d0d8c83.png)

**Comment by j28** [comment]
contacts functionality should not be included in any releases. i don't think we will work on it soon. is is possible to exclude it from the develop branch?

**Comment by CedrikNikita** [comment]
There is no such issue in current version.
