### ISSUE TITLE
[AirGap] Show connection option in Settings (mobile)

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#650]

**Comment by etharner** [comment]
We only have designs for main settings window in hardware wallets section: https://app.zeplin.io/project/59e4cf99fc0bb2f99a89551b/screen/5c62d6817fee003c05500230
Don't know how it should looks like when you click to wallet.

**Comment by j28** [comment]
the designs for the detail view are here: https://zpl.io/2pvWRrJ
