### ISSUE TITLE
Reduce size of a bundle

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-base#673]

**Comment by j28** [comment]
phase 1:
+ drop components package

phase 2:
+ more improvements

**Comment by davidyuk** [comment]
Depends on:
https://github.com/aeternity/aepp-sdk-js/pull/374
https://github.com/aeternity/aepp-sdk-js/pull/376
https://github.com/aeternity/aepp-sdk-js/pull/377
https://github.com/aeternity/aepp-sdk-js/pull/378
https://github.com/aeternity/aepp-sdk-js/pull/379
https://github.com/aeternity/aepp-sdk-js/issues/380
https://github.com/aeternity/aepp-sdk-js/issues/381
https://github.com/aeternity/aepp-sdk-js/issues/383
https://github.com/aeternity/aepp-sdk-js/pull/434
https://github.com/aeternity/aepp-sdk-js/issues/435
