### ISSUE TITLE
Make sure that Base aepp icons shows up in iOS search results (see screenshot)

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#691]

**Comment by j28** [comment]
![Image](https://i.imgur.com/zsoAlWJ.jpg)

**Comment by davidyuk** [comment]
I can't reproduce this on iOS Simulator
![Simulator Screen Shot - iPhone 8 - 2019-05-07 at 07 54 23](https://user-images.githubusercontent.com/9007851/57275025-6f3dac80-709d-11e9-923b-b2a78f90afd6.png)
