### ISSUE TITLE
quick id should have margin on mobile

### ISSUE THREAD

**Issue by muxe** [aeternity/aepp-base#70]
it takes full width

![screenshot from 2018-03-01 17-46-03](https://user-images.githubusercontent.com/356123/36857305-7f2d002e-1d78-11e8-9ccb-9df60f0fe73d.png)
https://app.zeplin.io/project/59e4cf99fc0bb2f99a89551b/screen/5a37e018b96bf702083cbacd

**Comment by davidyuk** [comment]
It is the issue of AeIdentity component since it width is always equal to 335px.
https://github.com/aeternity/aepp-components/blob/master/src/components/aeIdentity/aeIdentity.scss#L13

**Comment by davidyuk** [comment]
This design is outdated
