### ISSUE TITLE
Quick ID Manager should be called My Identities

### ISSUE THREAD

**Issue by muxe** [aeternity/aepp-base#74]
![screenshot from 2018-03-01 17-49-26](https://user-images.githubusercontent.com/356123/36857708-80bf7290-1d79-11e8-9f85-deb17c613a4b.png)
https://app.zeplin.io/project/59e4cf99fc0bb2f99a89551b/screen/5a589c3504b3caaec824eae3

**Comment by davidyuk** [comment]
This design in outdated
