### ISSUE TITLE
Different QR sizes on scan transaction screens

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-base#751]
| From regular transaction | From transaction in voting app |
|---|---|
| ![image](https://user-images.githubusercontent.com/7098449/57609022-67a46900-75b1-11e9-951f-419d39e98915.png) | ![image](https://user-images.githubusercontent.com/7098449/57609030-6c691d00-75b1-11e9-906a-bc96e7ec51c5.png) |

**Comment by davidyuk** [comment]
Hey! Please check AeQrCode example from the storybook. As I see, this is an issue of @zxing/library package.
