### ISSUE TITLE
If people haven't backed-up their key, i would show a continuous warning message

### ISSUE THREAD

**Issue by eminogrande** [aeternity/aepp-base#852]
Or a notification bubble at the settings icon in the right, maybe a red exclamation mark? Or a banner that is continuously shown on top like Trezor wallet does it.

**Comment by j28** [comment]
This can be done with the same notification format as the successful transaction. Like so:
- for icon use the (!) icon from the Settings view (Backup Recovery Phrase list item)
- Heading: Please Backup your Recover Phrase!
- subheading/text: Secure your funds to prevent loss.
- left button: TAKE SECURITY COURSE
- right button: BACKUP NOW (in magenta)
