### ISSUE TITLE
Metadata aex proposal

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#896]

**Comment by davidyuk** [comment]
related issue: https://github.com/aeternity/AEXs/issues/49

**Comment by j28** [comment]
https://forum.aeternity.com/t/aexpansion-proposal-aepps-metadata-format-specification/3987

**Comment by j28** [comment]
get input from piwo and aeknow dev

**Comment by j28** [comment]
to be listed we require:
+ has to have manifest
+ name
+ protocol
+ app url
+ icon

recommended:
+ description
+ category
+ banner
+ network (ex. uat testnet)
+ author

**Comment by davidyuk** [comment]
I have made a draft of web manifest members: https://hackmd.aepps.com/s/H1GpZQmdH
