### ISSUE TITLE
ZeroClientProvider's version of getBalance often wrong

### ISSUE THREAD

**Issue by okwme** [aeternity/aepp-base#9]
web3.eth.getBalance() returns an incorrect amount fairly often causing all balances to be updated with the wrong value and corrected when the return is accurate again. Might stem from ZeroClientProvider.

**Comment by okwme** [comment]
this is a problem with kovan. parity and infura can't keep their nodes synced

**Comment by davidyuk** [comment]
Currently, the Base app doesn't support Ethereum, so this issue is not actual anymore.
