### ISSUE TITLE
Settings view does not work in Develop/i18n branches

### ISSUE THREAD

**Issue by j28** [aeternity/aepp-base#970]

**Comment by davidyuk** [comment]
> dmitry.kostin 11:53 AM
[Error] TypeError: undefined is not a constructor (evaluating 'new Intl.PluralRules(e.state.languages.activeCode)') — languages.js:76
ie (chunk-vendors.763ca9b1.js:7:12025)
re (chunk-vendors.763ca9b1.js:7:11937)
ee (chunk-vendors.763ca9b1.js:7:11584)
_render (chunk-vendors.763ca9b1.js:7:23755)
r (chunk-vendors.763ca9b1.js:7:27793)
get (chunk-vendors.763ca9b1.js:7:30648)
nr (chunk-vendors.763ca9b1.js:7:30565)
Nn (chunk-vendors.763ca9b1.js:7:27806)
init (chunk-vendors.763ca9b1.js:7:20525)
n (chunk-vendors.763ca9b1.js:7:21845)
d (chunk-vendors.763ca9b1.js:7:44151)
p (chunk-vendors.763ca9b1.js:7:43780)
C (chunk-vendors.763ca9b1.js:7:46383)
k (chunk-vendors.763ca9b1.js:7:47172)
(anonymous function) (chunk-vendors.763ca9b1.js:7:48314)
_update (chunk-vendors.763ca9b1.js:7:26962)
r (chunk-vendors.763ca9b1.js:7:27783)
get (chunk-vendors.763ca9b1.js:7:30648)
run (chunk-vendors.763ca9b1.js:7:31380)
Xn (chunk-vendors.763ca9b1.js:7:29587)
(anonymous function) (chunk-vendors.763ca9b1.js:7:12743)
ue (chunk-vendors.763ca9b1.js:7:12135)
promiseReactionJob

**Comment by davidyuk** [comment]
Fixed by https://github.com/aeternity/aepp-base/pull/807/commits/2a4011ea92b8351f4eabd66c7be4bda4cd4011fd
