### ISSUE TITLE
left-more icon is smaller when language is set to russian

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-base#975]
![image](https://user-images.githubusercontent.com/7098449/60953928-7608ca00-a341-11e9-90c3-95ea832047da.png)

**Comment by CedrikNikita** [comment]
![image](https://user-images.githubusercontent.com/9008074/61021312-54acea00-a3e4-11e9-936c-13e25fee4af1.png)
This problem doesn't depend on language, it depends on message length
