### ISSUE TITLE
Wording: Avoid using contacts word due to their absence

### ISSUE THREAD

**Issue by CedrikNikita** [aeternity/aepp-base#992]
- [ ] Onboarding Send: Transfer to contacts and subaccounts. Receive by sharing your address.,
- [ ] Desktop Send: Paste the recipient address below. Or send to subaccounts, contacts or scan QR code.

**Comment by j28** [comment]
Transfer to accounts and subaccounts. Receive by sharing your address.

Paste the recipient address below, scan QR code or send to subaccounts.
